on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:
    name: Laravel-Tests
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: actions/checkout@v4
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Decrypt .env
        run: php artisan env:decrypt --key=${{ secrets.ENV_ENCRYPT_KEY }} --env=testing --filename=.env --force
      - name: Start Mysql
        run: |
          sudo /etc/init.d/mysql start
          mysql -u root --password=root -e "CREATE DATABASE IF NOT EXISTS rcms;"
#      - name: Directory Permissions
#        run: chmod -R 777 storage bootstrap/cache
      - name: Run migration
        run: php artisan migrate
#      - name: Npm install
#        run: npm install
#      - name: Compile assets
#        run: npm run dev
      - name: Execute PHPUnit tests
        run: php artisan test
